name: environment
channels:
  - conda-forge
dependencies:
  - appmode
  - numpy
  - sphinx-gallery
  - pandas
  - matplotlib
  - ipyvolume
  - ipywidgets
  - pandas       
  - scikit-learn
  - requests
  - python



