name: environment
channels:
  - conda-forge
dependencies:
  - appmode
  - numpy
  - nbgitpuller
  - sphinx-gallery
  - pandas
  - matplotlib
  - ipyvolume
  - ipywidgets
  - pandas       
  - urllib
  - scikit-learn
  - json
  - time
  - random
  - requests
  - warnings
  - python

